import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manually defined sidebar so we can place the 'Introduction to the FAR Exam' category
  tutorialSidebar: [
    { type: "doc", id: "intro" },
    {
      type: "category",
      label: "Introduction to the FAR Exam",
      items: [
        "introduction/index",
        "introduction/exam-overview-and-structure",
        "introduction/content-allocation",
        "introduction/skill-allocation",
      ],
    },
    {
      type: "category",
      label: "Financial Statements & Reporting",
      items: [
        "financial-statements/index",
        "financial-statements/balance-sheet",
        "financial-statements/income-statement",
        "financial-statements/comprehensive-income",
        "financial-statements/statement-of-changes-in-equity",
        "financial-statements/statement-of-cash-flows",
        "financial-statements/notes-to-financial-statements",
        "financial-statements/ratios-and-performance-metrics",
      ],
    },
    {
      type: "category",
      label: "Select Asset Accounts",
      items: [
        "assets/index",
        "assets/cash-and-receivables",
        "assets/inventory",
        "assets/property-plant-and-equipment",
        "assets/investments",
        "assets/intangible-assets",
      ],
    },
    {
      type: "category",
      label: "Select Liability & Equity Accounts",
      items: [
        "liabilities-equity/index",
        "liabilities-equity/payables-and-accrued-liabilities",
        "liabilities-equity/long-term-debt",
        "liabilities-equity/equity",
      ],
    },
    {
      type: "category",
      label: "Key Transaction Topics",
      items: [
        "key-transactions/index",
        "key-transactions/revenue-recognition",
        "key-transactions/income-taxes",
        "key-transactions/lessee-accounting",
        "key-transactions/accounting-changes-and-error-corrections",
        "key-transactions/contingencies-and-commitments",
        "key-transactions/fair-value-measurements",
        "key-transactions/subsequent-events",
      ],
    },
    {
      type: "category",
      label: "Advanced & Special Topics",
      items: [
        "advanced-topics/index",
        "advanced-topics/consolidated-financial-statements",
        "advanced-topics/public-company-reporting",
        "advanced-topics/special-purpose-frameworks",
      ],
    },
    {
      type: "category",
      label: "Not-for-Profit Accounting",
      items: [
        "not-for-profit/index",
        "not-for-profit/nfp-financial-statements",
        "not-for-profit/nfp-contributions",
      ],
    },
    {
      type: "category",
      label: "Governmental Accounting",
      items: ["governmental/index", "governmental/measurement-focus-and-funds"],
    },
    // keep the rest of the docs autogenerated under a separate autogenerated group
    // { type: "autogenerated", dirName: "." },
  ],
};

export default sidebars;
